# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title a random walk Metropolis sampler using R
#' @description a random walk Metropolis sampler using R
#' @param sigma the variances are used for the normal distribution
#' @param x0 Initial value of x
#' @param N the number of samples
#' @return a random sample of size
#' @examples
#' \dontrun{
#' N=2000
#' sigma=c(.05,.5,2,16)
#' x0=25
#' crw1=crw(sigma[1],x0,N)
#' crw2=crw(sigma[2],x0,N)
#' crw3=crw(sigma[3],x0,N)
#' crw4=crw(sigma[4],x0,N)
#' }
#' @export 
crw <- function(sigma, x0, N) {
    .Call('_test_crw', PACKAGE = 'test', sigma, x0, N)
}

